### ISSUE TITLE
Handle various cases for multiple EPI and Field Map sessions. 

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#134]
lets assume we have EPI1, EPI2, ... , EPIn and UNWARP1, UNWARP2, ... , UNWARPn. Then the pipeline should handle the following:

Case 1: You want to process EPIk with UNWARPk for k = 1, ..., n

Case 2: You want to process EPIk for k = 1,...,n with UNWARPj, where j takes one value from {1,...,n}. 

Case 3: You want to skip EPI1,...,EPIj where j < n and process EPI(j+1),..., EPIn with UNWARP(j+1),..., UNWARPn

Case 4: You want to process EPIj with UNWARPk and you want to skip processing all other EPI sessions.

**Comment by echumin** [comment]
Handled in release and also addressed by bids standards.
