### ISSUE TITLE
changing parcellations after T1_B has been run

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#138]
Currently, if a new parcellatiion is added AFTER running T1_B, the entire T1_B has to be re-run. However, this takes a long time and is unnecessary since the MNI transformations have already been calculated. 

If a new parcellation is to be included after already having run T1_B, we can add a flag indicating whether T1_B registration to MNI space has already been run and use those transformation matrices on new parcellations, instead of having to run all of T1_B.

**Comment by echumin** [comment]
Parcellation handling is now a separate flag. solved.
