### ISSUE TITLE
update config file

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#21]
The config file is somewhat messy at the moment. In some sections (specially the Nuisance Regression sections) it is difficult for the user to distinguish which flags are to be set/specified by the user, and which flags should not be modified by the user. 

So two things are needed to make this more clear:

1. Add more comments and instructions in the config file and highlight flags that are to be set by the user while making it clear which flags are set by the program once the user has specified their settings. Flags will always be set with the default values/settings that "we" (Jenya and Mario?) recommend but user may have data that has different processing needs

2. Add a description of each flag that the user can set in the documentation. Perhaps this is where we explain why/what settings "we" recommend, and offer suggestions for other settings if data is different...

**Comment by tharpm95** [comment]
Agree these changes would be useful. I'll put this on my agenda
