### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#4]
Andrea and Matt will work on this.

**Comment by echumin** [comment]
Some points to update:

- in the code **main_conn_pipeline.sh** is named **sample_main.sh**, need to make names consistent between code and documentation.
- Should clarify things like 'module' in the readme are specific to the IU supercomputing system and are not general instructions.
- is **pip install dipy --user** necessary? the text only describes **two** packages that are needed.
- maybe add the clarification that the **config** script must be pointed to in the **main** script if it is copied elsewhere and/or renamed.
- Add a clarification that **main.sh** must have executable permissions (which can go away if the file is copied elsewhere).
- Clearly state that the **main** script must stay in and be executed from the pipeline directory. The **config** file I think can be moved as long as its accurately pointed to in the **main (line47)** script.

**Comment by echumin** [comment]
README will be redone as the bidsywork branch becomes master.
