### ISSUE TITLE
t1_prepare_A - add an option to use the overlap mask as the brain mask. 

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#48]
This would have to be done after completing T1_prepare_A. Perhaps as a pre-processing option for T1_Prepare_B, or a "post_T1_prepare_A". 
The overlap mask needs to be renamed, and filled, then re-extraction needs to be done. 

This should all be clearly documented in the QC log to make sure we know that the overlap mask was used as the brain mask.

**Comment by echumin** [comment]
not sure there is a gain here; ANTS performs way better than BET.
