### ISSUE TITLE
Missing ConnPipelineSM preventing ants from running

### ISSUE THREAD

**Issue by echumin** [IUSCA/IUSM-ConnPipe#74]
```
 file /N/project/ConnPipelineSM/brainmask_templates/NKI/T_template.nii.gz does not exist . 
/N/soft/rhel7/ants/2.3.1/bin/antsBrainExtraction.sh: line 117: 26725 Segmentation fault      (core dumped) $cmd
```
How would I go about obtaining the supplementary files? I can't find a description of its location.

**Comment by aiavenak** [comment]
Shared SM with Jenya. Still need to find a way to put SM in a repository... are there any IU resources available for this? Or maybe use figshare?

**Comment by echumin** [comment]
Figshare might do the trick. One of us could put it on their IU Google Drive and provide a shareable link in the short term.
