### ISSUE TITLE
Missing error in log for dicom conversion (T1_A)

### ISSUE THREAD

**Issue by echumin** [IUSCA/IUSM-ConnPipe#75]
When dicom conversion fails (in my case due to wrong file extension specified in the config) this error is printed to terminal:
`###### DICOM 2 nifti ######

No dicom (.dcm) images found.
Please specify the correct file extension of dicom files by setting the configs_dcmFiles flag in the config file
Skipping further analysis
ERROR: problem at T1_PREPARE_A. exiting. `

But this message does not end up in the out log which looks like this:

`###### DICOM 2 nifti ######
### Tue Jun  1 10:44:38 EDT 2021 -
ERROR
problem at T1_PREPARE_A. exiting.
`
Can that be added to the log file? I may miss the error if I am running multiple subjects and not paying attention to the terminal.

**Comment by aiavenak** [comment]
I will create a new ticket because this is part of a more general problem with error printing.
