### ISSUE TITLE
Update seed connectivity script

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/IUSM-ConnPipe#99]
- Make compatible with new version of the pipeline
- Update how subject names are defined. Make consistent with fMRI_A plotting script

**Comment by aiavenak** [comment]
This entire script needs to be redone. 
The MNi -> native space transformations should be done inside the pipeline

**Comment by echumin** [comment]
This is a secondary utility script that is not part of the pipeline, so I am closing this issue.
